# Generated by Django 4.2.7 on 2025-03-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradis', '0007_service_is_confirmed_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 13)),
        ),
    ]
