# Generated by Django 4.2.6 on 2023-11-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradis', '0003_rename_servicebook_appointments_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
